### ISSUE TITLE
Uncaught exception 'GuzzleHttp\Exception\RequestException' with message 'cURL error 60: SSL certificate problem

### ISSUE THREAD

**Issue by dylanpiera** [teamreflex/DiscordPHP#112]
I'm trying to get the basic example bot working that is shown in the readme.php
But whenever I try to load it I get this error:

Fatal error: Uncaught GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in C:\Dev_enviorment\wamp64\www\Discord-Bot\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:187
Stack trace:
#0 C:\Dev_enviorment\wamp64\www\Discord-Bot\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(150): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 C:\Dev_enviorment\wamp64\www\Discord-Bot\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(103): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 C:\Dev_enviorment\wamp64\www\Discord-Bot\vendor\guzzlehttp\guzzle\src\Handler\CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#3 C in C:\Dev_enviorment\wamp64\www\Discord-Bot\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 187

this is the code in the php file
```
<?php

include __DIR__.'/vendor/autoload.php';

$token = 'MY_TOKEN';

use Discord\Discord;
use Discord\WebSockets\WebSocket;

$discord = new Discord($token);
$ws      = new WebSocket($discord);

$ws->on('ready', function ($discord) use ($ws) {
    echo "Bot is ready!".PHP_EOL;

    // We will listen for messages
    $ws->on('message', function ($message, $discord) {
        echo "Message from {$message->author->username}: {$message->content}".PHP_EOL;
    });
});

$ws->run();
```

**Comment by dylanpiera** [comment]
Fixed on the Discord-API chat

The fix was to follow these steps: http://stackoverflow.com/questions/21114371/php-curl-error-code-60

**Comment by Adambean** [comment]
This is NOT fixed. Telling users to simply install some random certificate authority we know nothing about is a terrible way to resolve this issue.

**Comment by aequasi** [comment]
Please have a little bit more grave when responding to issues. You are more likely to receive help when being courteous.

**Comment by aequasi** [comment]
As for who the cert is from... 

https://curl.haxx.se/docs/caextract.html
