### ISSUE TITLE
Class as callback

### ISSUE THREAD

**Issue by finalgamer** [teamreflex/DiscordPHP#160]
It would be really nice if we could register classes as callbacks.

Example
```php
$discord = new DiscordCommandClient(...);
$discord->registerCommand('name', [new NameCommand(), 'handle']); // Calls method handle()
$discord->registerCommand('name', [NameCommand::class, 'handle']); // Calls static method handle()
```

This form of callback is also a valid PHP callable and the array can be passed into call_user_func($callback)

**Comment by uniquoooo** [comment]
Should work now.

**Comment by siklr** [comment]
At first glance, unless I'm missing something, this is still not working in the master version.
